apiapp/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from apiapp import views as apiviews

router = routers.DefaultRouter() 
router.register(r'users', apiviews.UserViewSet) 
router.register(r'profile', apiviews.ProfileViewSet)

urlpatterns = [ 
	url(r'^', include(router.urls, namespace='api')), 
    url(r'^api-auth/', include('rest_framework.urls')),
]

authapp/urls.py
from django.conf.urls import include, url
from authapp import views
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^statistics', views.StatisticsView.as_view(), name='statistics'),
    url(r'^applications', views.AppView.as_view(), name='applications'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('authapp.urls', namespace='authapp')),
    url(r'^api/', include('apiapp.urls')),
    url(r'^profile/', include('profiles.urls', namespace='profiles')),
]

profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^edit/$',views.edit_profile, name="edit_profile"),
    # url('^account/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
]

apiapp/models.py
from django.db import models

# Create your models here.

authapp/models.py
from django.db import models

# Create your models here.

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    date_of_birth = models.DateField(null=True)
    university = models.CharField(max_length=50, blank=True)
    gpa = models.CharField(max_length=4)
    experience = models.CharField(max_length=2)
    def __str__(self):
        return self.user.username

    def age(self):
            import datetime
            dob = self.date_of_birth
            tod = datetime.date.today()
            my_age = (tod.year - dob.year) - int((tod.month, tod.day) < (dob.month, dob.day))
            return my_age

def create_profile(sender, **kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

profiles/forms.py
from django import forms
from profiles.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

class DateInput(forms.DateInput):
    input_type = 'date'
    
class ProfileForm(forms.ModelForm):
    template_name='profile.html'
    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'gender', 'city', 'date_of_birth', 'university', 'gpa', 'experience')
        widgets = {
            'date_of_birth': DateInput()
        }

apiapp/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from profiles.models import UserProfile
from rest_framework import routers, serializers, viewsets
from apiapp.serializers import UserSerializer, ProfileSerializer

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class ProfileViewSet(viewsets.ModelViewSet):
	queryset = UserProfile.objects.all()
	serializer_class = ProfileSerializer

authapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

class RegisterFormView(FormView):
    form_class = UserCreationForm

    # Ссылка, на которую будет перенаправляться пользователь в случае успешной регистрации.
    # В данном случае указана ссылка на страницу входа для зарегистрированных пользователей.
    success_url = "/login/"

    # Шаблон, который будет использоваться при отображении представления.
    template_name = "page-register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)

class LoginFormView(FormView):
    form_class = AuthenticationForm

    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "page-login.html"

    # В случае успеха перенаправим на главную.
    success_url = "/profile/edit"

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        # Выполняем выход для пользователя, запросившего данное представление.
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return HttpResponseRedirect("/")


class HomeView(TemplateView):
    template_name = 'index.html'

class AppView(TemplateView):
    template_name = 'application.html'

class StatisticsView(TemplateView):
    template_name = 'statistics.html'

profiles/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormView
from django.views.generic.base import View 
from django.contrib.auth.decorators import login_required
from profiles.forms import UserForm, ProfileForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .models import UserProfile
from django.views import generic
from django.db import transaction

class ProfileListView(generic.ListView):
    queryset = UserProfile.objects.select_related('user')

def get_user_profile(request, username):
    user = User.objects.get(User, username=username)
    return render(request, 'index.html', {"user":user})

def view_profile(request, pk=None):
    if pk:
        user = User.objiects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'index.html', args)

@login_required
@transaction.atomic
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('authapp:home')
        else:
            return redirect('authapp:home')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'page-profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

authapp/templates/account.html
{% extends 'base.html' %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    {% for profile in profile_list %}
	  {{ profile.user.username }}
	  {{ profile.bio }}
	{% endfor %}
{% endblock %}

authapp/templates/application.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HR-manager's dashboard</title>
   
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "assets/css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/themify-icons.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/flag-icon.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/cs-skin-elastic.css" %}">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="{% static "assets/scss/style.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                 <div class="profile clearfix">
                  <div class="profile_pic" style="width:35%; float:left;">
                    <img src="{% static "images/avatar/nargiz.jpg" %}" alt="..." class="img-circle profile_img">
                  </div>
                  <div class="profile_info">
                    <a class="navbar-brand" href="#">Welcome,</br>{{user.username}}</a>
                  </div>
                </div>
                
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
               <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'authapp:home' %}"> <i class="menu-icon fa fa-home"></i>Home </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'authapp:applications' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Applications</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-spinner"></i><a href="{% url 'authapp:applications' %}">Active</a></li>
                            
                        </ul>
                    </li>
                    
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'authapp:statistics' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Statistics</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-spinner"></i><a href="{% url 'authapp:statistics' %}">All</a></li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user"></i>Profile</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'authapp:login' %}">Login</a></li>
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'authapp:register' %}">Register</a></li>
                            
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        

        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Dashboard</a></li>
                            <li><a href="#">Applications</a></li>
                            <li class="active">Active</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3">
            <div class="animated fadeIn">
                <div class="row">
                     <div class="col-lg-4 col-md-6">
                        <aside class="profile-nav alt">
                            <section class="card">
                                <div style="margin:10px;text-align:center; font-size:16pt;">
                                    <h3>Project Manager</h3>  
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item"><a style="margin-left:10px; color:black;" href="#"> Alesya Samoylova, <i>23 y.o </i></a>
                                        <div class="user-area dropdown float-left"><img class="user-avatar rounded-circle" src="{% static "images/avatar/2.jpg" %}" alt="User Avatar">
                                        </div>
                                        
                                    </li>
                                    <li class="list-group-item"><a style="margin-left:10px; color:black;" href="#"> Alina Kim, <i>26 y.o </i></a>
                                        <div class="user-area dropdown float-left"><img class="user-avatar rounded-circle" src="{% static "images/avatar/4.jpg" %}"alt="User Avatar">
                                        </div>
                                        
                                    </li>
                                    <li class="list-group-item"><a style="margin-left:10px; color:black;" href="#">Evelina Gricenko, <i>25 y.o </i></a>
                                        <div class="user-area dropdown float-left"><img class="user-avatar rounded-circle" src="{% static "images/avatar/5.jpg" %}" alt="User Avatar">
                                        </div>
                                        
                                    </li>
                                    <li class="list-group-item"><a style="margin-left:10px; color:black;" href="#"> Viktoriya Lesova, <i>27 y.o </i></a>
                                        <div class="user-area dropdown float-left"><img class="user-avatar rounded-circle" src="{% static "images/avatar/3.jpg" %}" alt="User Avatar">
                                        </div>
                                    </li>
                                </ul>

                            </section>
                        </aside>
                    </div>
            
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">Experience </h4>
                                    <canvas id="barChart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">GPA</h4>
                                    <canvas id="team-chart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">University </h4>
                                    <canvas id="sales-chart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                       

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">Quality or Quantity </h4>
                                    <canvas id="lineChart"></canvas>
                                </div>
                            </div>
                        </div>

                            <div class="col-lg-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="mb-3">How long Efficiently </h4>
                                        <canvas id="doughutChart"></canvas>
                                    </div>
                                </div>
                            </div><!-- /# column -->

                        </div><!-- /# column -->

             



                </div>

                <div class="col-sm-12">
                    <h2>TOP THE BEST CANDIDATES </h2>
                <table class="table table-striped">
                  <thead>
                    <tr class="table-primary">
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Age</th>
                      <th scope="col">University</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr class="table-danger">
                      <th scope="row">1</th>
                      <td>Viktoriya Lesova</td>
                      <td>27</td>
                      <td>KBTU</td>
                    </tr>
                    <tr>
                      <th scope="row">2</th>
                      <td> Alesya Samoylova</td>
                      <td>23</td>
                      <td>SDU</td>
                    </tr>
                    <tr>
                      <th scope="row">3</th>
                      <td>Alina Kim</td>
                      <td>26</td>
                      <td>KIMEP</td>
                    </tr>
                    <tr>
                      <th scope="row">3</th>
                      <td>Evelina Gricenko</td>
                      <td>25</td>
                      <td>ALMAU</td>
                    </tr>
                  </tbody>
                </table>
            </div>

            </div><!-- .animated -->
        </div><!-- .content -->


    </div><!-- /#right-panel -->

    <!-- Right Panel -->


    <script src="{% static "assets/js/vendor/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "assets/js/popper.min.js" %}"></script>
    <script src="{% static "assets/js/plugins.js" %}"></script>
    <script src="{% static "assets/js/main.js" %}"></script>
        <!--  Chart js -->
    <script src="{% static "assets/js/lib/chart-js/Chart.bundle.js" %}"></script>
    <script src="{% static "assets/js/lib/chart-js/chartjs-init.js" %}"></script>

</body>
</html>

authapp/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
		
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						
						<ul class="icons">
							<li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li>
							<li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
							
						</ul>
						{% if user.is_authenticated %}
								<h1>Welcome, {{ user.username }}</h1>
						{% else %}
    						<p>Welcome, new user. Please log in.</p>
						{% endif %}
						
					</header>

				<!-- Main -->
				
					<section id="main">
						
				
					    <section class="thumbnails">
					      
							{% block content %}
								
							
                            {% endblock %}
					
						</section>
					</section>

				<!-- Footer -->
					<footer id="footer">
						
					</footer>

			</div>

			
	</body>
</html>

authapp/templates/login.html
{% extends 'base.html' %}

  

{% block content %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign in</button>
</form>
{% endblock %}

authapp/templates/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

authapp/templates/register.html
{% extends 'base.html' %}


{% block content %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

authapp/templates/statistics.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HR-manager's dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="{% static "assets/css/normalize.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/themify-icons.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/flag-icon.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/cs-skin-elastic.css" %}">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link rel="stylesheet" href="{% static "assets/scss/style.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                 <div class="profile clearfix">
                  <div class="profile_pic" style="width:35%; float:left;">
                    <img src="{% static "images/avatar/nargiz.jpg" %}" alt="..." class="img-circle profile_img">
                  </div>
                  <div class="profile_info">
                    <a class="navbar-brand" href="#">Welcome,</br>{{ user.username}}</a>
                  </div>
                </div>
                
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'authapp:home' %}"> <i class="menu-icon fa fa-home"></i>Home </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'authapp:applications' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Applications</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-spinner"></i><a href="{% url 'authapp:applications' %}">Active</a></li>
                            
                        </ul>
                    </li>
                    
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'authapp:statistics' %}" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Statistics</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="fa fa-spinner"></i><a href="{% url 'authapp:statistics' %}">All</a></li>
                        </ul>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user"></i>Profile</a>
                        <ul class="sub-menu children dropdown-menu">
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'authapp:login' %}">Login</a></li>
                            <li><i class="menu-icon fa fa-sign-in"></i><a href="{% url 'authapp:register' %}">Register</a></li>
                            
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li><a href="#">Dashboard</a></li>
                            <li><a href="#">Applications</a></li>
                            <li class="active">Active</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3">
            <div class="animated fadeIn">
                <div class="row">
                 
            
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">TOP IT UNIVERSITIES </h4>
                                    <canvas id="barChart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">TOP BUSINESS UNIVERSITIES</h4>
                                    <canvas id="team-chart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">TOP  UNIVERSITIES FOR ECONOMICS </h4>
                                    <canvas id="sales-chart"></canvas>
                                </div>
                            </div>
                        </div><!-- /# column -->

                       

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="mb-3">TOP UNIVERSITIES OF MANAGEMENT</h4>
                                    <canvas id="lineChart"></canvas>
                                </div>
                            </div>
                        </div>

                    </div><!-- /# column -->
            </div><!-- .animated -->
        </div><!-- .content -->


    </div><!-- /#right-panel -->

    <!-- Right Panel -->


    <script src="{% static "assets/js/vendor/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "assets/js/popper.min.js" %}"></script>
    <script src="{% static "assets/js/plugins.js" %}"></script>
    <script src="{% static "assets/js/main.js" %}"></script>
        <!--  Chart js -->
    <script src="{% static "assets/js/lib/chartjs/Chart.bundle.js" %}"></script>
    <script src="{% static "assets/js/lib/chartjs/chartjs-init.js" %}"></script>

</body>
</html>